# Generated by Django 2.2 on 2021-06-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Exercise', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Workout', max_length=50),
            preserve_default=False,
        ),
    ]
