# Generated by Django 2.2 on 2021-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0002_auto_20210611_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
