# Generated by Django 2.2 on 2021-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0003_auto_20210611_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='swolemates_app.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='swolemates_app.User'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_workouts', to='swolemates_app.User'),
        ),
    ]
