# Generated by Django 2.2 on 2021-06-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0004_auto_20210611_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
