# Generated by Django 2.2 on 2021-06-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0005_auto_20210611_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, null=True, to='swolemates_app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_friends_+', to='swolemates_app.User'),
        ),
    ]
