# Generated by Django 2.2 on 2021-06-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0006_auto_20210611_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fav_exercises',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
