# Generated by Django 2.2 on 2021-06-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0007_auto_20210614_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_exercises',
            field=models.TextField(blank=True, null=True),
        ),
    ]
