# Generated by Django 2.2 on 2021-06-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0008_auto_20210614_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='sent_requests', to='swolemates_app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='swolemates_app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='swolemates_app.User'),
        ),
    ]
