# Generated by Django 2.2 on 2021-06-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swolemates_app', '0011_auto_20210617_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='swolemates_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend_request',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='swolemates_app.User'),
            preserve_default=False,
        ),
    ]
